"""afegir taula exclusions temes globals

Revision ID: 02175d40aa18
Revises: 3a78a83ca019
Create Date: 2025-12-11 11:18:29.847885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02175d40aa18'
down_revision = '3a78a83ca019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temes_exclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('data_exclusio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['paisos.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['temes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tema_id', 'pais_id', name='uq_tema_pais_exclusio')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('temes_exclusions')
    # ### end Alembic commands ###
