"""base schema

Revision ID: 06d92f714f28
Revises: 
Create Date: 2025-12-08 14:08:42.337825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d92f714f28'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codi_iso', sa.String(length=2), nullable=False),
    sa.Column('nom_oficial_en', sa.String(length=100), nullable=False),
    sa.Column('revisat_per_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codi_iso')
    )
    op.create_table('traduccions_ubicacions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipus', sa.String(length=20), nullable=False),
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipus', 'element_id', 'idioma', name='traduccio_unica')
    )
    op.create_index('idx_traduccio_lookup', 'traduccions_ubicacions', ['tipus', 'element_id', 'idioma'], unique=False)
    op.create_table('usuaris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_login', sa.String(length=80), nullable=False),
    sa.Column('contrasenya_hash', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('primer_cognom', sa.String(length=100), nullable=False),
    sa.Column('segon_cognom', sa.String(length=100), nullable=True),
    sa.Column('municipi_naixement', sa.String(length=100), nullable=True),
    sa.Column('regio_naixement', sa.String(length=100), nullable=True),
    sa.Column('data_naixement', sa.String(length=20), nullable=True),
    sa.Column('pais_naixement', sa.String(length=100), nullable=True),
    sa.Column('idioma', sa.String(length=50), nullable=True),
    sa.Column('pais_residencia', sa.String(length=100), nullable=True),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('identificador_abadia', sa.String(length=64), nullable=True),
    sa.Column('nivell_usuari', sa.String(length=10), nullable=True),
    sa.Column('data_registre', sa.DateTime(), nullable=True),
    sa.Column('rebre_missatges', sa.Boolean(), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('email_verificat', sa.Boolean(), nullable=False),
    sa.Column('token_verificacio', sa.String(length=100), nullable=True),
    sa.Column('data_token', sa.DateTime(), nullable=True),
    sa.Column('token_reset_password', sa.String(length=100), nullable=True),
    sa.Column('data_token_reset', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identificador_abadia'),
    sa.UniqueConstraint('nom_login'),
    sa.UniqueConstraint('token_reset_password'),
    sa.UniqueConstraint('token_verificacio')
    )
    op.create_table('biografia_seccions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('contingut', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('data_modificacio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories_tema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pais_id'], ['paisos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('contacte_id', sa.Integer(), nullable=False),
    sa.Column('nom_personalitzat', sa.String(length=100), nullable=True),
    sa.Column('data_afegit', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contacte_id'], ['usuaris.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuari_id', 'contacte_id', name='_usuari_contacte_uc')
    )
    op.create_table('entrades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=255), nullable=True),
    sa.Column('tema', sa.String(length=255), nullable=True),
    sa.Column('any_text', sa.String(length=10), nullable=True),
    sa.Column('contingut', sa.Text(), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('regio', sa.String(length=100), nullable=True),
    sa.Column('municipi', sa.String(length=100), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('titol_imatge', sa.String(length=255), nullable=True),
    sa.Column('descripcio_imatge', sa.Text(), nullable=True),
    sa.Column('any_imatge', sa.String(length=10), nullable=True),
    sa.Column('pais_imatge', sa.String(length=100), nullable=True),
    sa.Column('regio_imatge', sa.String(length=100), nullable=True),
    sa.Column('municipi_imatge', sa.String(length=100), nullable=True),
    sa.Column('referencia', sa.String(length=255), nullable=True),
    sa.Column('nom_fitxer', sa.String(length=255), nullable=True),
    sa.Column('visible_publicament', sa.Boolean(), nullable=True),
    sa.Column('es_publica', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tipus_fitxer', sa.String(length=10), nullable=True),
    sa.Column('tipus_media', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrades_blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('contingut', sa.Text(), nullable=False),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.Column('firma', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('espais_familiars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('motiu', sa.String(length=100), nullable=True),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('periode_referencia', sa.String(length=50), nullable=True),
    sa.Column('heraldica_fitxer', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_home', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_arbre', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_membres', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_records', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_documents', sa.String(length=255), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('creat_per_id', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('visible_globalment', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['creat_per_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('missatges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('emissor_id', sa.Integer(), nullable=False),
    sa.Column('receptor_id', sa.Integer(), nullable=False),
    sa.Column('assumpte', sa.String(length=150), nullable=False),
    sa.Column('contingut', sa.Text(), nullable=False),
    sa.Column('llegit', sa.Boolean(), nullable=True),
    sa.Column('data_env', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emissor_id'], ['usuaris.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organitzacions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('tipus', sa.String(length=20), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('regio', sa.String(length=100), nullable=False),
    sa.Column('municipi', sa.String(length=100), nullable=False),
    sa.Column('codi_postal', sa.String(length=20), nullable=True),
    sa.Column('url_publica', sa.String(length=100), nullable=True),
    sa.Column('url_personalitzada', sa.String(length=200), nullable=True),
    sa.Column('color_primary', sa.String(length=7), nullable=True),
    sa.Column('logo_fitxer', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_home', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_historia', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_entrades', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_membres', sa.String(length=255), nullable=True),
    sa.Column('imatge_card_imatges', sa.String(length=255), nullable=True),
    sa.Column('es_premium', sa.Boolean(), nullable=True),
    sa.Column('data_premium', sa.Date(), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('creat_per_id', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('email_adabida', sa.String(length=200), nullable=False),
    sa.Column('email_extern', sa.String(length=200), nullable=True),
    sa.Column('telefon_contacte', sa.String(length=20), nullable=True),
    sa.Column('adresa', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['creat_per_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_publica')
    )
    op.create_table('perfil_biografic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('primer_cognom', sa.String(length=100), nullable=True),
    sa.Column('segon_cognom', sa.String(length=100), nullable=True),
    sa.Column('professio', sa.String(length=120), nullable=True),
    sa.Column('frase_destacada', sa.String(length=255), nullable=True),
    sa.Column('imatge_perfil', sa.String(length=255), nullable=True),
    sa.Column('mostrar_biografia', sa.Boolean(), nullable=True),
    sa.Column('mostrar_contacte', sa.Boolean(), nullable=True),
    sa.Column('mostrar_data_naixement', sa.Boolean(), nullable=True),
    sa.Column('mostrar_ubicacio', sa.Boolean(), nullable=True),
    sa.Column('mostrar_origen_familiar', sa.Boolean(), nullable=True),
    sa.Column('pais_naixement', sa.String(length=100), nullable=True),
    sa.Column('regio_naixement', sa.String(length=100), nullable=True),
    sa.Column('municipi_naixement', sa.String(length=100), nullable=True),
    sa.Column('data_naixement', sa.Date(), nullable=True),
    sa.Column('pare_nom', sa.String(length=100), nullable=True),
    sa.Column('pare_primer_cognom', sa.String(length=100), nullable=True),
    sa.Column('pare_segon_cognom', sa.String(length=100), nullable=True),
    sa.Column('pare_data_naixement', sa.Date(), nullable=True),
    sa.Column('pare_pais_naixement', sa.String(length=100), nullable=True),
    sa.Column('pare_regio_naixement', sa.String(length=100), nullable=True),
    sa.Column('pare_municipi_naixement', sa.String(length=100), nullable=True),
    sa.Column('pare_pais_defuncio', sa.String(length=100), nullable=True),
    sa.Column('pare_regio_defuncio', sa.String(length=100), nullable=True),
    sa.Column('pare_municipi_defuncio', sa.String(length=100), nullable=True),
    sa.Column('pare_data_defuncio', sa.Date(), nullable=True),
    sa.Column('mare_pais_naixement', sa.String(length=100), nullable=True),
    sa.Column('mare_regio_naixement', sa.String(length=100), nullable=True),
    sa.Column('mare_municipi_naixement', sa.String(length=100), nullable=True),
    sa.Column('mare_pais_defuncio', sa.String(length=100), nullable=True),
    sa.Column('mare_regio_defuncio', sa.String(length=100), nullable=True),
    sa.Column('mare_municipi_defuncio', sa.String(length=100), nullable=True),
    sa.Column('mare_data_defuncio', sa.Date(), nullable=True),
    sa.Column('mare_nom', sa.String(length=100), nullable=True),
    sa.Column('mare_primer_cognom', sa.String(length=100), nullable=True),
    sa.Column('mare_segon_cognom', sa.String(length=100), nullable=True),
    sa.Column('mare_data_naixement', sa.Date(), nullable=True),
    sa.Column('codi_identificacio', sa.String(length=128), nullable=True),
    sa.Column('mostrar_experiencia', sa.Boolean(), nullable=True),
    sa.Column('mostrar_estudis', sa.Boolean(), nullable=True),
    sa.Column('mostrar_obres', sa.Boolean(), nullable=True),
    sa.Column('mostrar_carrecs', sa.Boolean(), nullable=True),
    sa.Column('mostrar_pare', sa.Boolean(), nullable=True),
    sa.Column('mostrar_mare', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codi_identificacio')
    )
    op.create_table('regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['paisos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traduccions_paisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pais_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['pais_id'], ['paisos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pais_id', 'idioma', name='traduccio_pais_unica')
    )
    op.create_table('arxius_adjuntats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('nom_fitxer', sa.String(length=255), nullable=False),
    sa.Column('tipus', sa.String(length=50), nullable=True),
    sa.Column('tipus_media', sa.String(length=20), nullable=True),
    sa.Column('data_pujada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arxius_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_fitxer', sa.String(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biografia_familia_seccions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familia_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('contingut', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('data_modificacio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['familia_id'], ['espais_familiars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biografia_organitzacio_seccions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organitzacio_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('contingut', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('data_modificacio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organitzacio_id'], ['organitzacions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carrecs_publics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=150), nullable=False),
    sa.Column('any_inici', sa.Integer(), nullable=True),
    sa.Column('any_fi', sa.Integer(), nullable=True),
    sa.Column('municipi', sa.String(length=100), nullable=True),
    sa.Column('regio', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_biografic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('lloc_municipi', sa.String(length=100), nullable=True),
    sa.Column('lloc_regio', sa.String(length=100), nullable=True),
    sa.Column('lloc_pais', sa.String(length=100), nullable=True),
    sa.Column('data_conversa', sa.Date(), nullable=True),
    sa.Column('durada_minuts', sa.Integer(), nullable=True),
    sa.Column('observacions_generals', sa.Text(), nullable=True),
    sa.Column('arxiu_nom', sa.String(length=255), nullable=True),
    sa.Column('arxiu_tipus', sa.String(length=50), nullable=True),
    sa.Column('arxiu_tamany', sa.BigInteger(), nullable=True),
    sa.Column('organitzacio_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organitzacio_id'], ['organitzacions.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('denuncies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=False),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('data_revisio', sa.DateTime(), nullable=True),
    sa.Column('revisat_per_id', sa.Integer(), nullable=True),
    sa.Column('notes_admin', sa.Text(), nullable=True),
    sa.Column('accio', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.ForeignKeyConstraint(['revisat_per_id'], ['usuaris.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrades_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('espai_familiar_id', sa.Integer(), nullable=False),
    sa.Column('data_compartit', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.ForeignKeyConstraint(['espai_familiar_id'], ['espais_familiars.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entrada_id', 'espai_familiar_id', name='entrada_fam_unique')
    )
    op.create_table('entrades_guardades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrades_organitzacions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=False),
    sa.Column('organitzacio_id', sa.Integer(), nullable=False),
    sa.Column('data_compartit', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.ForeignKeyConstraint(['organitzacio_id'], ['organitzacions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entrada_id', 'organitzacio_id', name='entrada_org_unique')
    )
    op.create_table('estudis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('titulacio', sa.String(length=200), nullable=False),
    sa.Column('centre', sa.String(length=200), nullable=True),
    sa.Column('ciutat', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('any_inici', sa.Integer(), nullable=True),
    sa.Column('any_fi', sa.Integer(), nullable=True),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_biografic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('carrec', sa.String(length=200), nullable=False),
    sa.Column('organitzacio', sa.String(length=200), nullable=True),
    sa.Column('ambit', sa.String(length=100), nullable=True),
    sa.Column('any_inici', sa.Integer(), nullable=True),
    sa.Column('any_fi', sa.Integer(), nullable=True),
    sa.Column('actualment', sa.Boolean(), nullable=True),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_biografic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exposicions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=150), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=False),
    sa.Column('codi', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=50), nullable=False),
    sa.Column('any', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('carpeta', sa.String(length=300), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codi')
    )
    op.create_table('membres_familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=True),
    sa.Column('espai_familiar_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('data_adhesio', sa.DateTime(), nullable=True),
    sa.Column('pais_actual', sa.String(length=100), nullable=True),
    sa.Column('regio_actual', sa.String(length=100), nullable=True),
    sa.Column('municipi_actual', sa.String(length=100), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('primer_cognom', sa.String(length=100), nullable=True),
    sa.Column('segon_cognom', sa.String(length=100), nullable=True),
    sa.Column('data_naixement', sa.Date(), nullable=True),
    sa.Column('municipi_naixement', sa.String(length=200), nullable=True),
    sa.Column('regio_naixement', sa.String(length=200), nullable=True),
    sa.Column('pais_naixement', sa.String(length=200), nullable=True),
    sa.Column('data_defuncio', sa.Date(), nullable=True),
    sa.Column('municipi_defuncio', sa.String(length=200), nullable=True),
    sa.Column('regio_defuncio', sa.String(length=200), nullable=True),
    sa.Column('pais_defuncio', sa.String(length=200), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('genere', sa.String(length=10), nullable=True),
    sa.Column('pare_id', sa.Integer(), nullable=True),
    sa.Column('mare_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['espai_familiar_id'], ['espais_familiars.id'], ),
    sa.ForeignKeyConstraint(['mare_id'], ['membres_familia.id'], ),
    sa.ForeignKeyConstraint(['pare_id'], ['membres_familia.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuari_id', 'espai_familiar_id', name='usuari_familia_unique')
    )
    op.create_table('membres_organitzacio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('organitzacio_id', sa.Integer(), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.Column('data_adhesio', sa.DateTime(), nullable=True),
    sa.Column('data_sortida', sa.DateTime(), nullable=True),
    sa.Column('mostrar_entrades', sa.Boolean(), nullable=True),
    sa.Column('mostrar_perfil', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organitzacio_id'], ['organitzacions.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuari_id', 'organitzacio_id', name='usuari_organitzacio_unique')
    )
    op.create_table('missatges_organitzacio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organitzacio_id', sa.Integer(), nullable=False),
    sa.Column('emissor_id', sa.Integer(), nullable=False),
    sa.Column('receptor_id', sa.Integer(), nullable=True),
    sa.Column('assumpte', sa.String(length=150), nullable=False),
    sa.Column('contingut', sa.Text(), nullable=False),
    sa.Column('llegit', sa.Boolean(), nullable=True),
    sa.Column('tipus', sa.String(length=10), nullable=True),
    sa.Column('data_env', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['emissor_id'], ['usuaris.id'], ),
    sa.ForeignKeyConstraint(['organitzacio_id'], ['organitzacions.id'], ),
    sa.ForeignKeyConstraint(['receptor_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('regio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['regio_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('any', sa.Integer(), nullable=False),
    sa.Column('nom_fitxer', sa.String(length=255), nullable=False),
    sa.Column('ruta_relativa', sa.String(length=500), nullable=False),
    sa.Column('ext', sa.String(length=10), nullable=True),
    sa.Column('tipus', sa.String(length=10), nullable=True),
    sa.Column('mida_bytes', sa.Integer(), nullable=True),
    sa.Column('titol', sa.String(length=200), nullable=True),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('creat_el', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfil_biografic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peticions_testimoni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=200), nullable=False),
    sa.Column('descripcio', sa.Text(), nullable=True),
    sa.Column('completada', sa.Boolean(), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('data_completada', sa.DateTime(), nullable=True),
    sa.Column('resposta_usuari_id', sa.Integer(), nullable=True),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.ForeignKeyConstraint(['resposta_usuari_id'], ['usuaris.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicituds_organitzacio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('organitzacio_id', sa.Integer(), nullable=False),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.Column('data_solicitud', sa.DateTime(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('missatge', sa.Text(), nullable=True),
    sa.Column('notes_admin', sa.Text(), nullable=True),
    sa.Column('processat_per_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organitzacio_id'], ['organitzacions.id'], ),
    sa.ForeignKeyConstraint(['processat_per_id'], ['usuaris.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuari_id', 'organitzacio_id', 'estat', name='usuari_org_estat_unique')
    )
    op.create_table('temes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('aplicar_a_tots_paisos', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categories_tema.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temes_forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.Column('tancat', sa.Boolean(), nullable=True),
    sa.Column('fixat', sa.Boolean(), nullable=True),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('data_ultim_missatge', sa.DateTime(), nullable=True),
    sa.Column('nombre_respostes', sa.Integer(), nullable=True),
    sa.Column('nombre_visites', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categories_forum.id'], ),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicacions_actuals_familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espai_familiar_id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('regio', sa.String(length=100), nullable=False),
    sa.Column('municipi', sa.String(length=100), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('es_provisional', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['espai_familiar_id'], ['espais_familiars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ubicacions_origen_familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espai_familiar_id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('regio', sa.String(length=100), nullable=False),
    sa.Column('municipi', sa.String(length=100), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['espai_familiar_id'], ['espais_familiars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversa_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('primer_cognom', sa.String(length=100), nullable=False),
    sa.Column('segon_cognom', sa.String(length=100), nullable=True),
    sa.Column('data_naixement', sa.Date(), nullable=True),
    sa.Column('lloc_municipi', sa.String(length=100), nullable=True),
    sa.Column('lloc_regio', sa.String(length=100), nullable=True),
    sa.Column('lloc_pais', sa.String(length=100), nullable=True),
    sa.Column('observacions', sa.Text(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents_membres_familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('membre_familia_id', sa.Integer(), nullable=False),
    sa.Column('tipus_document', sa.String(length=50), nullable=True),
    sa.Column('nom_fitxer', sa.String(length=255), nullable=False),
    sa.Column('descripcio', sa.String(length=500), nullable=True),
    sa.Column('visibilitat', sa.String(length=20), nullable=True),
    sa.Column('data_pujada', sa.DateTime(), nullable=True),
    sa.Column('pujat_per_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['membre_familia_id'], ['membres_familia.id'], ),
    sa.ForeignKeyConstraint(['pujat_per_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imatges_galeria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_id', sa.Integer(), nullable=True),
    sa.Column('exposicio_id', sa.Integer(), nullable=True),
    sa.Column('nom_fitxer', sa.String(length=255), nullable=False),
    sa.Column('destinacio', sa.String(length=50), nullable=True),
    sa.Column('data_publicacio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entrada_id'], ['entrades.id'], ),
    sa.ForeignKeyConstraint(['exposicio_id'], ['exposicions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matrimonis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espai_familiar_id', sa.Integer(), nullable=False),
    sa.Column('membre_1_id', sa.Integer(), nullable=False),
    sa.Column('membre_2_id', sa.Integer(), nullable=False),
    sa.Column('data_casament', sa.Date(), nullable=True),
    sa.Column('data_fi', sa.Date(), nullable=True),
    sa.Column('estat', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['espai_familiar_id'], ['espais_familiars.id'], ),
    sa.ForeignKeyConstraint(['membre_1_id'], ['membres_familia.id'], ),
    sa.ForeignKeyConstraint(['membre_2_id'], ['membres_familia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missatges_forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('usuari_id', sa.Integer(), nullable=False),
    sa.Column('contingut', sa.Text(), nullable=False),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('data_modificacio', sa.DateTime(), nullable=True),
    sa.Column('editat', sa.Boolean(), nullable=True),
    sa.Column('moderat', sa.Boolean(), nullable=True),
    sa.Column('motiu_moderacio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tema_id'], ['temes_forum.id'], ),
    sa.ForeignKeyConstraint(['usuari_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imatges_exposicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imatge_id', sa.Integer(), nullable=False),
    sa.Column('ruta_expo', sa.String(length=255), nullable=False),
    sa.Column('data_afegit', sa.DateTime(), nullable=True),
    sa.Column('exposicio_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exposicio_id'], ['exposicions.id'], ),
    sa.ForeignKeyConstraint(['imatge_id'], ['imatges_galeria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imatges_exposicio')
    op.drop_table('missatges_forum')
    op.drop_table('matrimonis')
    op.drop_table('imatges_galeria')
    op.drop_table('documents_membres_familia')
    op.drop_table('conversa_participant')
    op.drop_table('ubicacions_origen_familia')
    op.drop_table('ubicacions_actuals_familia')
    op.drop_table('temes_forum')
    op.drop_table('temes')
    op.drop_table('solicituds_organitzacio')
    op.drop_table('peticions_testimoni')
    op.drop_table('obres')
    op.drop_table('municipis')
    op.drop_table('missatges_organitzacio')
    op.drop_table('membres_organitzacio')
    op.drop_table('membres_familia')
    op.drop_table('exposicions')
    op.drop_table('experiencies')
    op.drop_table('estudis')
    op.drop_table('entrades_organitzacions')
    op.drop_table('entrades_guardades')
    op.drop_table('entrades_families')
    op.drop_table('denuncies')
    op.drop_table('conversa')
    op.drop_table('carrecs_publics')
    op.drop_table('biografia_organitzacio_seccions')
    op.drop_table('biografia_familia_seccions')
    op.drop_table('arxius_entrada')
    op.drop_table('arxius_adjuntats')
    op.drop_table('traduccions_paisos')
    op.drop_table('regions')
    op.drop_table('perfil_biografic')
    op.drop_table('organitzacions')
    op.drop_table('missatges')
    op.drop_table('espais_familiars')
    op.drop_table('entrades_blog')
    op.drop_table('entrades')
    op.drop_table('contactes')
    op.drop_table('categories_tema')
    op.drop_table('biografia_seccions')
    op.drop_table('usuaris')
    op.drop_index('idx_traduccio_lookup', table_name='traduccions_ubicacions')
    op.drop_table('traduccions_ubicacions')
    op.drop_table('paisos')
    op.drop_table('categories_forum')
    # ### end Alembic commands ###
