"""Afegir visible_public a MembreFamilia

Revision ID: 0bd7109465b6
Revises: ace3bf283b61
Create Date: 2026-09-08 11:16:05.990432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bd7109465b6'
down_revision = 'ace3bf283b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membres_familia', sa.Column('visible_public', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('membres_familia', 'visible_public', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membres_familia', 'visible_public')
    # ### end Alembic commands ###
