"""afegir notes_metodologiques_publiques a Conversa

Revision ID: 10db577360d6
Revises: 53ebbef64a35
Create Date: 2026-01-24 11:38:03.130798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10db577360d6'
down_revision = '53ebbef64a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversa', sa.Column('notes_metodologiques_publiques', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversa', 'notes_metodologiques_publiques')
    # ### end Alembic commands ###
