"""afegir visible_publicament a EspaiFamiliar

Revision ID: 1a686916533c
Revises: 0bd7109465b6
Create Date: 2026-09-08 22:43:06.305638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a686916533c'
down_revision = '0bd7109465b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('espais_familiars', sa.Column('visible_publicament', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('espais_familiars', 'visible_publicament')
    # ### end Alembic commands ###
