"""afegir camps imatge_card a Usuari

Revision ID: 1e0524aeb67c
Revises: c47509796134
Create Date: 2026-08-25 11:04:45.346864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e0524aeb67c'
down_revision = 'c47509796134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuaris', sa.Column('imatge_card_biografia', sa.String(length=255), nullable=True))
    op.add_column('usuaris', sa.Column('imatge_card_entrades', sa.String(length=255), nullable=True))
    op.add_column('usuaris', sa.Column('imatge_card_nova_entrada', sa.String(length=255), nullable=True))
    op.add_column('usuaris', sa.Column('imatge_card_perfil', sa.String(length=255), nullable=True))
    op.add_column('usuaris', sa.Column('imatge_card_organitzacions', sa.String(length=255), nullable=True))
    op.add_column('usuaris', sa.Column('imatge_card_familia', sa.String(length=255), nullable=True))
    op.add_column('usuaris', sa.Column('imatge_card_conversa', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuaris', 'imatge_card_conversa')
    op.drop_column('usuaris', 'imatge_card_familia')
    op.drop_column('usuaris', 'imatge_card_organitzacions')
    op.drop_column('usuaris', 'imatge_card_perfil')
    op.drop_column('usuaris', 'imatge_card_nova_entrada')
    op.drop_column('usuaris', 'imatge_card_entrades')
    op.drop_column('usuaris', 'imatge_card_biografia')
    # ### end Alembic commands ###
