"""afegir titol i descripcio a DocumentFamilia individual

Revision ID: 30fc65ea5943
Revises: dc1133ba8d06
Create Date: 2026-09-12 00:49:26.948670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30fc65ea5943'
down_revision = 'dc1133ba8d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_familia', sa.Column('titol', sa.String(length=200), nullable=True))
    op.add_column('documents_familia', sa.Column('descripcio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents_familia', 'descripcio')
    op.drop_column('documents_familia', 'titol')
    # ### end Alembic commands ###
