"""Afegir visibilitat_dades a MembreFamilia i tipus_missatge a Missatge

Revision ID: 314482dd8bdf
Revises: c4532786548d
Create Date: 2025-12-28 20:10:22.340510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314482dd8bdf'
down_revision = 'c4532786548d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membres_familia', sa.Column('visibilitat_dades', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membres_familia', 'visibilitat_dades')
    # ### end Alembic commands ###
