"""Afegir traduccions categories

Revision ID: 31f658e9bcc9
Revises: cc2f0add26eb
Create Date: 2026-01-08 10:28:11.790252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31f658e9bcc9'
down_revision = 'cc2f0add26eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traduccions_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categories_tema.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', 'idioma', name='traduccio_categoria_unica')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traduccions_categories')
    # ### end Alembic commands ###
