"""afegir camps titol, any_arxiu, pais, regio, municipi, descripcio, referencia a ArxiuAdjunt

Revision ID: 32390bfc7bfb
Revises: e238ea85aff3
Create Date: 2026-08-14 17:16:04.285675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32390bfc7bfb'
down_revision = 'e238ea85aff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arxius_adjuntats', sa.Column('titol', sa.String(length=255), nullable=True))
    op.add_column('arxius_adjuntats', sa.Column('any_arxiu', sa.Integer(), nullable=True))
    op.add_column('arxius_adjuntats', sa.Column('pais', sa.String(length=100), nullable=True))
    op.add_column('arxius_adjuntats', sa.Column('regio', sa.String(length=100), nullable=True))
    op.add_column('arxius_adjuntats', sa.Column('municipi', sa.String(length=100), nullable=True))
    op.add_column('arxius_adjuntats', sa.Column('descripcio', sa.Text(), nullable=True))
    op.add_column('arxius_adjuntats', sa.Column('referencia', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arxius_adjuntats', 'referencia')
    op.drop_column('arxius_adjuntats', 'descripcio')
    op.drop_column('arxius_adjuntats', 'municipi')
    op.drop_column('arxius_adjuntats', 'regio')
    op.drop_column('arxius_adjuntats', 'pais')
    op.drop_column('arxius_adjuntats', 'any_arxiu')
    op.drop_column('arxius_adjuntats', 'titol')
    # ### end Alembic commands ###
