"""Afegir taula traduccions_temes

Revision ID: 3a78a83ca019
Revises: 31fd6bef1c29
Create Date: 2025-12-10 10:44:40.808604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a78a83ca019'
down_revision = '31fd6bef1c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traduccions_temes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['temes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tema_id', 'idioma', name='traduccio_tema_unica')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traduccions_temes')
    # ### end Alembic commands ###
