"""Afegir camp bandera_preferida a usuari

Revision ID: 40cf6559250c
Revises: 06d92f714f28
Create Date: 2025-12-09 10:44:29.329637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40cf6559250c'
down_revision = '06d92f714f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
