"""afegir_camps_entrevista_adabida_a_conversa

Revision ID: 4b2c8963db7e
Revises: 8efff48cba0e
Create Date: 2026-01-14 20:19:28.051656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2c8963db7e'
down_revision = '8efff48cba0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversa', sa.Column('tipus_conversa', sa.String(length=50), nullable=True))
    op.add_column('conversa', sa.Column('titol', sa.String(length=255), nullable=True))
    op.add_column('conversa', sa.Column('tema', sa.String(length=255), nullable=True))
    op.add_column('conversa', sa.Column('contingut', sa.Text(), nullable=True))
    op.add_column('conversa', sa.Column('consentiment_informat', sa.Boolean(), nullable=True))
    op.add_column('conversa', sa.Column('notes_preparacio', sa.Text(), nullable=True))
    op.add_column('conversa', sa.Column('notes_camp', sa.Text(), nullable=True))
    op.add_column('conversa', sa.Column('observacions_post', sa.Text(), nullable=True))
    op.add_column('conversa', sa.Column('visible_publicament', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversa', 'visible_publicament')
    op.drop_column('conversa', 'observacions_post')
    op.drop_column('conversa', 'notes_camp')
    op.drop_column('conversa', 'notes_preparacio')
    op.drop_column('conversa', 'consentiment_informat')
    op.drop_column('conversa', 'contingut')
    op.drop_column('conversa', 'tema')
    op.drop_column('conversa', 'titol')
    op.drop_column('conversa', 'tipus_conversa')
    # ### end Alembic commands ###
