"""Afegir taula tema_categoria per relacio N:M

Revision ID: 4e5690deaa8f
Revises: 02175d40aa18
Create Date: 2025-12-14 00:37:56.840773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5690deaa8f'
down_revision = '02175d40aa18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tema_categoria',
    sa.Column('tema_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categories_tema.id'], ),
    sa.ForeignKeyConstraint(['tema_id'], ['temes.id'], ),
    sa.PrimaryKeyConstraint('tema_id', 'categoria_id')
    )
    
    # ✅ COPIAR dades existents
    op.execute("""
        INSERT INTO tema_categoria (tema_id, categoria_id)
        SELECT id, categoria_id FROM temes WHERE categoria_id IS NOT NULL
    """)
    
    op.alter_column('temes', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temes', 'categoria_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_table('tema_categoria')
    # ### end Alembic commands ###
