"""Afegir camp lloc_institucio a Conversa

Revision ID: 53ebbef64a35
Revises: 9a660cc858aa
Create Date: 2026-01-22 09:51:22.585639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ebbef64a35'
down_revision = '9a660cc858aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversa', sa.Column('lloc_institucio', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversa', 'lloc_institucio')
    # ### end Alembic commands ###
