"""Afegir camp foto a MembreFamilia

Revision ID: 6ca142a3ccc1
Revises: 314482dd8bdf
Create Date: 2025-12-29 09:58:36.216848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca142a3ccc1'
down_revision = '314482dd8bdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('membres_familia', sa.Column('foto', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('membres_familia', 'foto')
    # ### end Alembic commands ###
