"""afegir titol i any a DocumentFamilia

Revision ID: 758c8814c257
Revises: 8c5e912823b0
Create Date: 2026-09-11 12:52:04.235399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758c8814c257'
down_revision = '8c5e912823b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_familia', sa.Column('titol', sa.String(length=200), nullable=True))
    op.add_column('documents_familia', sa.Column('any_document', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents_familia', 'any_document')
    op.drop_column('documents_familia', 'titol')
    # ### end Alembic commands ###
