"""afegir camp es_conversa a ArxiuAdjunt

Revision ID: 831e4e56f0b4
Revises: 32390bfc7bfb
Create Date: 2026-08-16 00:25:51.229952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831e4e56f0b4'
down_revision = '32390bfc7bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arxius_adjuntats', sa.Column('es_conversa', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arxius_adjuntats', 'es_conversa')
    # ### end Alembic commands ###
