"""afegir taula DocumentFamilia

Revision ID: 8c5e912823b0
Revises: 1a686916533c
Create Date: 2026-09-11 12:21:18.867419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c5e912823b0'
down_revision = '1a686916533c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents_familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espai_familiar_id', sa.Integer(), nullable=False),
    sa.Column('nom_fitxer', sa.String(length=255), nullable=False),
    sa.Column('tipus', sa.String(length=10), nullable=True),
    sa.Column('descripcio', sa.String(length=500), nullable=True),
    sa.Column('visible_public', sa.Boolean(), nullable=False),
    sa.Column('data_pujada', sa.DateTime(), nullable=True),
    sa.Column('pujat_per_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['espai_familiar_id'], ['espais_familiars.id'], ),
    sa.ForeignKeyConstraint(['pujat_per_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents_familia')
    # ### end Alembic commands ###
