"""Afegir traduccions categories portada

Revision ID: 8efff48cba0e
Revises: 31f658e9bcc9
Create Date: 2026-01-08 11:20:11.916751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efff48cba0e'
down_revision = '31f658e9bcc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traduccions_categories_portada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=5), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id', 'idioma', name='traduccio_categoria_portada_unica')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('traduccions_categories_portada')
    # ### end Alembic commands ###
