"""afegir_entrada_id_a_conversa

Revision ID: 9a660cc858aa
Revises: 4b2c8963db7e
Create Date: 2026-01-14 21:00:02.621968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a660cc858aa'
down_revision = '4b2c8963db7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversa', sa.Column('entrada_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'conversa', 'entrades', ['entrada_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversa', type_='foreignkey')
    op.drop_column('conversa', 'entrada_id')
    # ### end Alembic commands ###
