"""Afegeix taula pagines_publiques

Revision ID: 9e56e0ff8a0a
Revises: 30fc65ea5943
Create Date: 2026-09-23 21:30:34.280647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e56e0ff8a0a'
down_revision = '30fc65ea5943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagines_publiques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipus_entitat', sa.String(length=20), nullable=False),
    sa.Column('entitat_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=30), server_default='classic', nullable=False),
    sa.Column('lema', sa.String(length=200), nullable=True),
    sa.Column('imatge_portada', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('data_creacio', sa.DateTime(), nullable=True),
    sa.Column('data_modificacio', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipus_entitat', 'entitat_id', name='uq_pagina_publica_entitat')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagines_publiques')
    # ### end Alembic commands ###
