"""Afegir any_inici i any_final a BiografiaSeccion

Revision ID: ac185fac63e3
Revises: 4e5690deaa8f
Create Date: 2025-12-14 21:51:47.389294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac185fac63e3'
down_revision = '4e5690deaa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biografia_seccions', sa.Column('any_inici', sa.Integer(), nullable=True))
    op.add_column('biografia_seccions', sa.Column('any_final', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biografia_seccions', 'any_final')
    op.drop_column('biografia_seccions', 'any_inici')
    # ### end Alembic commands ###
