"""Afegir model ArxiuMissatge per adjunts a missatges

Revision ID: ace3bf283b61
Revises: 1e0524aeb67c
Create Date: 2026-08-31 22:18:08.255315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace3bf283b61'
down_revision = '1e0524aeb67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxius_missatges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('missatge_id', sa.Integer(), nullable=False),
    sa.Column('nom_fitxer', sa.String(length=255), nullable=False),
    sa.Column('tipus', sa.String(length=50), nullable=True),
    sa.Column('tipus_media', sa.String(length=20), nullable=True),
    sa.Column('data_pujada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['missatge_id'], ['missatges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arxius_missatges')
    # ### end Alembic commands ###
