"""afegir camp es_portada a ArxiuAdjunt

Revision ID: c47509796134
Revises: 831e4e56f0b4
Create Date: 2026-08-21 11:23:53.956856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c47509796134'
down_revision = '831e4e56f0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arxius_adjuntats', sa.Column('es_portada', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arxius_adjuntats', 'es_portada')
    # ### end Alembic commands ###
