"""Eliminar categoria_id de Tema - usar només N:M

Revision ID: cc2f0add26eb
Revises: 6ca142a3ccc1
Create Date: 2026-01-07 22:48:16.271015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2f0add26eb'
down_revision = '6ca142a3ccc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_membre_matrimoni_id'), table_name='membres_familia')
    op.drop_constraint(op.f('fk_membre_matrimoni'), 'membres_familia', type_='foreignkey')
    op.create_foreign_key(None, 'membres_familia', 'matrimonis', ['matrimoni_id'], ['id'])
    op.drop_constraint(op.f('temes_categoria_id_fkey'), 'temes', type_='foreignkey')
    op.drop_column('temes', 'categoria_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('temes', sa.Column('categoria_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('temes_categoria_id_fkey'), 'temes', 'categories_tema', ['categoria_id'], ['id'])
    op.drop_constraint(None, 'membres_familia', type_='foreignkey')
    op.create_foreign_key(op.f('fk_membre_matrimoni'), 'membres_familia', 'matrimonis', ['matrimoni_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_membre_matrimoni_id'), 'membres_familia', ['matrimoni_id'], unique=False)
    # ### end Alembic commands ###
