"""reestructurar documents de familia en grups

Revision ID: dc1133ba8d06
Revises: 758c8814c257
Create Date: 2026-09-12 00:32:58.862947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc1133ba8d06'
down_revision = '758c8814c257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grups_documents_familia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espai_familiar_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=200), nullable=True),
    sa.Column('descripcio', sa.String(length=500), nullable=True),
    sa.Column('visible_public', sa.Boolean(), nullable=False),
    sa.Column('data_pujada', sa.DateTime(), nullable=True),
    sa.Column('pujat_per_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['espai_familiar_id'], ['espais_familiars.id'], ),
    sa.ForeignKeyConstraint(['pujat_per_id'], ['usuaris.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents_familia', sa.Column('grup_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('documents_familia_espai_familiar_id_fkey'), 'documents_familia', type_='foreignkey')
    op.drop_constraint(op.f('documents_familia_pujat_per_id_fkey'), 'documents_familia', type_='foreignkey')
    op.create_foreign_key(None, 'documents_familia', 'grups_documents_familia', ['grup_id'], ['id'])
    op.drop_column('documents_familia', 'espai_familiar_id')
    op.drop_column('documents_familia', 'visible_public')
    op.drop_column('documents_familia', 'descripcio')
    op.drop_column('documents_familia', 'pujat_per_id')
    op.drop_column('documents_familia', 'titol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents_familia', sa.Column('titol', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('documents_familia', sa.Column('pujat_per_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents_familia', sa.Column('descripcio', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('documents_familia', sa.Column('visible_public', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('documents_familia', sa.Column('espai_familiar_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'documents_familia', type_='foreignkey')
    op.create_foreign_key(op.f('documents_familia_pujat_per_id_fkey'), 'documents_familia', 'usuaris', ['pujat_per_id'], ['id'])
    op.create_foreign_key(op.f('documents_familia_espai_familiar_id_fkey'), 'documents_familia', 'espais_familiars', ['espai_familiar_id'], ['id'])
    op.drop_column('documents_familia', 'grup_id')
    op.drop_table('grups_documents_familia')
    # ### end Alembic commands ###
