"""afegir data_modificacio a Entrada

Revision ID: e238ea85aff3
Revises: fbdb95a6a59c
Create Date: 2026-08-13 11:06:56.942045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e238ea85aff3'
down_revision = 'fbdb95a6a59c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entrades', sa.Column('data_modificacio', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entrades', 'data_modificacio')
    # ### end Alembic commands ###
