"""afegir imatge_card_nova_entrada i imatge_card_conversa a Usuari

Revision ID: f36877ed1ae9
Revises: 1e0524aeb67c
Create Date: 2026-08-26 10:06:59.782304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f36877ed1ae9'
down_revision = '1e0524aeb67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
