"""afegir usuari_id, mida, descripcio a imatges_galeria

Revision ID: fbdb95a6a59c
Revises: 10db577360d6
Create Date: 2026-08-08 22:35:27.308025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdb95a6a59c'
down_revision = '10db577360d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imatges_galeria', sa.Column('usuari_id', sa.Integer(), nullable=True))
    op.add_column('imatges_galeria', sa.Column('mida', sa.String(), nullable=True))
    op.add_column('imatges_galeria', sa.Column('descripcio', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'imatges_galeria', 'usuaris', ['usuari_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imatges_galeria', type_='foreignkey')
    op.drop_column('imatges_galeria', 'descripcio')
    op.drop_column('imatges_galeria', 'mida')
    op.drop_column('imatges_galeria', 'usuari_id')
    # ### end Alembic commands ###
